# pyre-unsafe
"""Compatibility exports for established EBB routing TestConfigs."""

from taac.abstractions.compatibility.eos_bgpcpp_compatibility import (  # noqa: F401
    ACL_COMMANDS as ACL_COMMANDS,
    ADD_INTERN_USER_IDS_CMD as ADD_INTERN_USER_IDS_CMD,
    BGPCPP_DAEMONS as BGPCPP_DAEMONS,
    EBB_BGPCPP_LOGGING_CONFIG as EBB_BGPCPP_LOGGING_CONFIG,
    FIBAGENT_BGP_CONF_B64 as FIBAGENT_BGP_CONF_B64,
    FIBAGENT_BGP_CONF_DEPLOY_CMD as FIBAGENT_BGP_CONF_DEPLOY_CMD,
    FIBAGENT_BGP_CONF_DEVICE_PATH as FIBAGENT_BGP_CONF_DEVICE_PATH,
    FIBAGENT_CONF_B64 as FIBAGENT_CONF_B64,
    FIBAGENT_CONF_DEPLOY_CMD as FIBAGENT_CONF_DEPLOY_CMD,
    FIBAGENT_CONF_DEVICE_PATH as FIBAGENT_CONF_DEVICE_PATH,
    INTERN_USER_IDS as INTERN_USER_IDS,
    PEERGROUP_BGP_MON as PEERGROUP_BGP_MON,
    PEERGROUP_EBGP_V4 as PEERGROUP_EBGP_V4,
    PEERGROUP_EBGP_V6 as PEERGROUP_EBGP_V6,
    PEERGROUP_IBGP_V4 as PEERGROUP_IBGP_V4,
    PEERGROUP_IBGP_V6 as PEERGROUP_IBGP_V6,
    POST_ACL_RESTART_DAEMONS as POST_ACL_RESTART_DAEMONS,
    REQUIRE_THRIFT_ACL_FILES_CMD as REQUIRE_THRIFT_ACL_FILES_CMD,
    THRIFT_ACL_FILES as THRIFT_ACL_FILES,
    UPDATE_GROUP_ALLOW_SLOW_PEER_DETACH as UPDATE_GROUP_ALLOW_SLOW_PEER_DETACH,
    UPDATE_GROUP_CONFIG as UPDATE_GROUP_CONFIG,
    UPDATE_GROUP_ENABLE_SERIALIZE_GROUP_PDU as UPDATE_GROUP_ENABLE_SERIALIZE_GROUP_PDU,
    UPDATE_GROUP_SLOW_PEER_BLOCK_COUNT_THRESHOLD as UPDATE_GROUP_SLOW_PEER_BLOCK_COUNT_THRESHOLD,
    UPDATE_GROUP_SLOW_PEER_BLOCK_COUNT_WINDOW_MS as UPDATE_GROUP_SLOW_PEER_BLOCK_COUNT_WINDOW_MS,
    UPDATE_GROUP_SLOW_PEER_TIME_THRESHOLD_MS as UPDATE_GROUP_SLOW_PEER_TIME_THRESHOLD_MS,
    UPDATE_GROUP_VERIFICATION_CMD as UPDATE_GROUP_VERIFICATION_CMD,
    VERIFY_THRIFT_ACL_USER_IDS_CMD as VERIFY_THRIFT_ACL_USER_IDS_CMD,
)
from taac.abstractions.compatibility.legacy_ebb_binding import (  # noqa: F401
    IXIA03_BGP_MON_IC_PARENT_NETWORK as IXIA03_BGP_MON_IC_PARENT_NETWORK,
    IXIA03_EBGP_IC_PARENT_NETWORK_V4 as IXIA03_EBGP_IC_PARENT_NETWORK_V4,
    IXIA03_EBGP_IC_PARENT_NETWORK_V6 as IXIA03_EBGP_IC_PARENT_NETWORK_V6,
    IXIA03_IBGP_IC_PARENT_NETWORK_V4_DC_PLANE1 as IXIA03_IBGP_IC_PARENT_NETWORK_V4_DC_PLANE1,
    IXIA03_IBGP_IC_PARENT_NETWORK_V4_DC_PLANE2 as IXIA03_IBGP_IC_PARENT_NETWORK_V4_DC_PLANE2,
    IXIA03_IBGP_IC_PARENT_NETWORK_V4_DC_PLANE3 as IXIA03_IBGP_IC_PARENT_NETWORK_V4_DC_PLANE3,
    IXIA03_IBGP_IC_PARENT_NETWORK_V4_DC_PLANE4 as IXIA03_IBGP_IC_PARENT_NETWORK_V4_DC_PLANE4,
    IXIA03_IBGP_IC_PARENT_NETWORK_V4_MP_PLANE1 as IXIA03_IBGP_IC_PARENT_NETWORK_V4_MP_PLANE1,
    IXIA03_IBGP_IC_PARENT_NETWORK_V4_MP_PLANE2 as IXIA03_IBGP_IC_PARENT_NETWORK_V4_MP_PLANE2,
    IXIA03_IBGP_IC_PARENT_NETWORK_V4_MP_PLANE3 as IXIA03_IBGP_IC_PARENT_NETWORK_V4_MP_PLANE3,
    IXIA03_IBGP_IC_PARENT_NETWORK_V4_MP_PLANE4 as IXIA03_IBGP_IC_PARENT_NETWORK_V4_MP_PLANE4,
    IXIA03_IBGP_IC_PARENT_NETWORK_V6_DC_PLANE1 as IXIA03_IBGP_IC_PARENT_NETWORK_V6_DC_PLANE1,
    IXIA03_IBGP_IC_PARENT_NETWORK_V6_DC_PLANE2 as IXIA03_IBGP_IC_PARENT_NETWORK_V6_DC_PLANE2,
    IXIA03_IBGP_IC_PARENT_NETWORK_V6_DC_PLANE3 as IXIA03_IBGP_IC_PARENT_NETWORK_V6_DC_PLANE3,
    IXIA03_IBGP_IC_PARENT_NETWORK_V6_DC_PLANE4 as IXIA03_IBGP_IC_PARENT_NETWORK_V6_DC_PLANE4,
    IXIA03_IBGP_IC_PARENT_NETWORK_V6_MP_PLANE1 as IXIA03_IBGP_IC_PARENT_NETWORK_V6_MP_PLANE1,
    IXIA03_IBGP_IC_PARENT_NETWORK_V6_MP_PLANE2 as IXIA03_IBGP_IC_PARENT_NETWORK_V6_MP_PLANE2,
    IXIA03_IBGP_IC_PARENT_NETWORK_V6_MP_PLANE3 as IXIA03_IBGP_IC_PARENT_NETWORK_V6_MP_PLANE3,
    IXIA03_IBGP_IC_PARENT_NETWORK_V6_MP_PLANE4 as IXIA03_IBGP_IC_PARENT_NETWORK_V6_MP_PLANE4,
    IXIA_BGP_MON_IC_PARENT_NETWORK as IXIA_BGP_MON_IC_PARENT_NETWORK,
    IXIA_EBGP_IC_PARENT_NETWORK_V4 as IXIA_EBGP_IC_PARENT_NETWORK_V4,
    IXIA_EBGP_IC_PARENT_NETWORK_V6 as IXIA_EBGP_IC_PARENT_NETWORK_V6,
    IXIA_IBGP_IC_PARENT_NETWORK_V4_DC_PLANE1 as IXIA_IBGP_IC_PARENT_NETWORK_V4_DC_PLANE1,
    IXIA_IBGP_IC_PARENT_NETWORK_V4_DC_PLANE2 as IXIA_IBGP_IC_PARENT_NETWORK_V4_DC_PLANE2,
    IXIA_IBGP_IC_PARENT_NETWORK_V4_DC_PLANE3 as IXIA_IBGP_IC_PARENT_NETWORK_V4_DC_PLANE3,
    IXIA_IBGP_IC_PARENT_NETWORK_V4_DC_PLANE4 as IXIA_IBGP_IC_PARENT_NETWORK_V4_DC_PLANE4,
    IXIA_IBGP_IC_PARENT_NETWORK_V4_MP_PLANE1 as IXIA_IBGP_IC_PARENT_NETWORK_V4_MP_PLANE1,
    IXIA_IBGP_IC_PARENT_NETWORK_V4_MP_PLANE2 as IXIA_IBGP_IC_PARENT_NETWORK_V4_MP_PLANE2,
    IXIA_IBGP_IC_PARENT_NETWORK_V4_MP_PLANE3 as IXIA_IBGP_IC_PARENT_NETWORK_V4_MP_PLANE3,
    IXIA_IBGP_IC_PARENT_NETWORK_V4_MP_PLANE4 as IXIA_IBGP_IC_PARENT_NETWORK_V4_MP_PLANE4,
    IXIA_IBGP_IC_PARENT_NETWORK_V6_DC_PLANE1 as IXIA_IBGP_IC_PARENT_NETWORK_V6_DC_PLANE1,
    IXIA_IBGP_IC_PARENT_NETWORK_V6_DC_PLANE2 as IXIA_IBGP_IC_PARENT_NETWORK_V6_DC_PLANE2,
    IXIA_IBGP_IC_PARENT_NETWORK_V6_DC_PLANE3 as IXIA_IBGP_IC_PARENT_NETWORK_V6_DC_PLANE3,
    IXIA_IBGP_IC_PARENT_NETWORK_V6_DC_PLANE4 as IXIA_IBGP_IC_PARENT_NETWORK_V6_DC_PLANE4,
    IXIA_IBGP_IC_PARENT_NETWORK_V6_MP_PLANE1 as IXIA_IBGP_IC_PARENT_NETWORK_V6_MP_PLANE1,
    IXIA_IBGP_IC_PARENT_NETWORK_V6_MP_PLANE2 as IXIA_IBGP_IC_PARENT_NETWORK_V6_MP_PLANE2,
    IXIA_IBGP_IC_PARENT_NETWORK_V6_MP_PLANE3 as IXIA_IBGP_IC_PARENT_NETWORK_V6_MP_PLANE3,
    IXIA_IBGP_IC_PARENT_NETWORK_V6_MP_PLANE4 as IXIA_IBGP_IC_PARENT_NETWORK_V6_MP_PLANE4,
    IXIA_IPV4_START_OFFSET as IXIA_IPV4_START_OFFSET,
    IXIA_IPV6_START_OFFSET as IXIA_IPV6_START_OFFSET,
)
from taac.abstractions.compatibility.legacy_ebb_topology import (  # noqa: F401
    BGP_MON_PEER_COUNT as BGP_MON_PEER_COUNT,
    BGP_MON_REMOTE_AS as BGP_MON_REMOTE_AS,
    EBB_BGP_HOLD_TIMER_S as EBB_BGP_HOLD_TIMER_S,
    EBB_BGP_KEEPALIVE_TIMER_S as EBB_BGP_KEEPALIVE_TIMER_S,
    EBB_DEVICE_PER_PEER_MAX_ROUTE_LIMIT as EBB_DEVICE_PER_PEER_MAX_ROUTE_LIMIT,
    EBB_DEVICE_PREFIX_LIMIT as EBB_DEVICE_PREFIX_LIMIT,
    EBB_DEVICE_ROUTE_LIMIT as EBB_DEVICE_ROUTE_LIMIT,
    EBGP_PEER_COUNT_V4 as EBGP_PEER_COUNT_V4,
    EBGP_PEER_COUNT_V6 as EBGP_PEER_COUNT_V6,
    EBGP_REMOTE_AS as EBGP_REMOTE_AS,
    IBGP_PEER_SCALE_PER_PLANE as IBGP_PEER_SCALE_PER_PLANE,
    IBGP_REMOTE_AS as IBGP_REMOTE_AS,
)
from taac.constants import BgpPlusPlusProfile


EBB_EBGP_ROUTE_COUNT = 1_000_000
EBB_EBGP_V6_ROUTE_FILE = "ipv6_1M_routes.txt"
EBB_EBGP_V4_ROUTE_FILE = "ipv4_1M_routes.txt"

EBGP_PEER_TO_DRAIN = 4
IBGP_PEER_TO_DRAIN_PER_PLANE = 2
IBGP_DC_PLANE_COUNT = 4
DRAIN_POOL_PEER_COUNT = (
    EBGP_PEER_TO_DRAIN * 2 + IBGP_PEER_TO_DRAIN_PER_PLANE * IBGP_DC_PLANE_COUNT * 2
)

DEFAULT_PROFILE = BgpPlusPlusProfile.BGP_PLUS_PLUS_WITH_OPEN_R


def _derive_test_config_name(
    physical_inventory,  # noqa: ANN001
    workflow: str,
    enable_update_group: bool,
) -> str:
    """Return the canonical TestConfig name for an inventory and workflow."""
    short_name = physical_inventory.device_name.split(".")[0].upper()
    variant = "_UG" if enable_update_group else ""
    return f"{short_name}_{workflow}_TEST_CONFIG{variant}"
