# Copyright (c) Meta Platforms, Inc. and affiliates.
# pyre-unsafe
import typing as t

from taac.health_checks.abstract_health_check import (
    AbstractIxiaHealthCheck,
)
# `StatViewAssistant` is re-exported as a Union[Ixn, Uhd] from taac_ixia — match
# the type that `get_or_create_stat_view` returns so type-check passes.
from taac.ixia.taac_ixia import (
    StatViewAssistant,
    TaacIxia as Ixia,
)
from taac.utils.common import async_everpaste_str
from taac.utils.oss_taac_lib_utils import retryable
from taac.health_check.health_check import types as hc_types
from tabulate import tabulate


# Cumulative counters compared against the per-run baseline.
FAULT_COUNTERS = ("CRC Errors", "Local Faults", "Remote Faults")

# Informational columns: reported, never thresholded. Absent on some port types
# / IxNetwork builds, so they are read defensively (see `_row_get`). Link State
# and Link Fault State are point-in-time and separate "flapped and recovered"
# from "still faulted right now"; the PCS counters are the PCS-layer view of the
# same fault signalling.
INFO_COLUMNS = (
    "Link State",
    "Link Fault State",
    "PCS Local Faults",
    "PCS Remote Faults",
)

# 802.3 clause 46 link-fault signalling: the station whose *receive* path
# fails sees Local Fault; its partner, signalled via Remote Fault ordered
# sets, sees Remote Fault. Keysight's IxExplorer Link Fault Signaling docs
# define the counters from the local port's perspective ("A Local Fault means
# that the local device stopped receiving valid data or signal from the
# remote device; a Remote Fault is generated by the remote device indicating
# that it stopped receiving valid data or signal from the local device"), and
# the stat schema exposes separate Local/RemoteOrderedSetsReceived counters
# for the raw ordered-set message counts — so "Local Faults"/"Remote Faults"
# count fault states seen BY this port, which is the mapping below.
# https://downloads.ixiacom.com/library/user_guides/IxOS/9.39/9.39_Rev_A/IxExplorer/IxExplorer_HTML5/Content/Topics/PortProperties_T400GD-8P-OSFP/PortProps_T400GD-8P-OSFP_LFS.htm
DIRECTION_CAVEAT = (
    "NOTE: the Local/Remote Faults -> direction mapping follows Keysight's "
    "documented semantics (Local Fault = this IXIA port stopped receiving; "
    "Remote Fault = the DUT reported it stopped receiving)."
)

# Counters identify the direction that lost RX, never which component in that
# direction broke.
DIRECTION_BY_COUNTER = {
    "Remote Faults": "RX loss in the IXIA->DUT direction (IXIA TX / cable / DUT RX)",
    "Local Faults": "RX loss in the DUT->IXIA direction (DUT TX / cable / IXIA RX)",
    "CRC Errors": (
        "frame corruption in the DUT->IXIA direction (DUT TX / cable / IXIA RX)"
    ),
}

# Cap on the inline (non-everpaste) portion of the failure message.
MAX_INLINE_ROWS = 5


class IxiaPortStatsHealthCheck(AbstractIxiaHealthCheck[hc_types.BaseHealthCheckIn]):
    CHECK_NAME = hc_types.CheckName.IXIA_PORT_STATS_CHECK

    async def _run(
        self,
        obj: Ixia,
        input: hc_types.BaseHealthCheckIn,
        check_params: t.Dict[str, t.Any],
    ) -> hc_types.HealthCheckResult:
        self.enable_fault_statistics(obj)
        # Use cached StatViewAssistant — subscription/ready-wait happens once
        # per test run, not on every HC invocation. ~10-15s saved per call after
        # the first.
        port_statistics_view = obj.get_or_create_stat_view("Port Statistics")
        with obj.stat_view_snapshot():
            latest_stats = self.get_port_statistics(port_statistics_view)

        # The fault counters are cumulative since port ownership, so faults
        # accrued while the links trained during setup would fail every later
        # invocation. Compare against a baseline instead. `snapshot_baseline`
        # (re)takes it explicitly; otherwise the first invocation in a test
        # takes it, which for a pre/post pair is the precheck.
        # Link State / Link Fault State are point-in-time, not cumulative, so
        # they are asserted on every invocation — including the baseline one:
        # a link that is dead right now must fail the precheck even though the
        # counters are exempt while the baseline is taken.
        link_failures = self.verify_link_state(latest_stats)

        if check_params.get("snapshot_baseline", False) or (
            obj.port_fault_baseline is None
        ):
            self.snapshot_fault_baseline(obj, latest_stats)
            if link_failures:
                return hc_types.HealthCheckResult(
                    status=hc_types.HealthCheckStatus.FAIL,
                    message=f"Snapshotted the IXIA fault-counter baseline, but "
                    f"link(s) are unhealthy right now: {'; '.join(link_failures)}",
                )
            return hc_types.HealthCheckResult(
                status=hc_types.HealthCheckStatus.PASS,
                message=f"Snapshotted the IXIA fault-counter baseline for "
                f"{len(latest_stats)} port(s).",
            )

        deltas, regressed = self.compute_fault_deltas(
            latest_stats, obj.port_fault_baseline
        )
        if regressed:
            # Counters below the baseline mean something cleared port stats
            # since it was taken (port re-acquisition, an explicit clear). A
            # stale baseline masks every subsequent fault on that port, so
            # re-baseline just those ports — their deltas are already clamped
            # to 0 and the other ports keep their real deltas.
            self.logger.warning(
                f"IXIA fault counters dropped below the baseline on {regressed}; "
                f"re-snapshotting the baseline for those ports."
            )
            self.snapshot_fault_baseline(obj, latest_stats, ports=regressed)

        exceeded_thresholds = self.verify_port_stats_threshold(deltas)

        if exceeded_thresholds:
            directions = self.attribute_fault_direction(exceeded_thresholds)
            # Use the Everpaste URL directly; it is already a clickable internalfb.com
            # link, so the throttled fburl tier (createFBUrl) is unnecessary here.
            everpaste_url = await async_everpaste_str(
                tabulate(exceeded_thresholds, headers="keys", tablefmt="simple_grid")
                + "\n\nFault direction:\n"
                + "\n".join(directions)
                + f"\n\n{DIRECTION_CAVEAT}"
            )
            inline_rows = exceeded_thresholds[:MAX_INLINE_ROWS]
            inline_summary = "; ".join(
                f"{row['identifier']}: CRC={row['CRC Errors']}, "
                f"LocalFaults={row['Local Faults']}, "
                f"RemoteFaults={row['Remote Faults']}"
                for row in inline_rows
            )
            suffix = (
                f" (+{len(exceeded_thresholds) - MAX_INLINE_ROWS} more)"
                if len(exceeded_thresholds) > MAX_INLINE_ROWS
                else ""
            )
            # Truncate the direction lines by PORT (same ports as the inline
            # summary), not by line — one port emits up to 4 lines and would
            # otherwise crowd the other ports out of the inline message.
            inline_directions = self.attribute_fault_direction(inline_rows)
            return hc_types.HealthCheckResult(
                status=hc_types.HealthCheckStatus.FAIL,
                message=f"IXIA port fault counters increased since the baseline: "
                f"{inline_summary}{suffix}. "
                f"{'; '.join(inline_directions)}. "
                f"Full details: {everpaste_url}",
            )
        if link_failures:
            return hc_types.HealthCheckResult(
                status=hc_types.HealthCheckStatus.FAIL,
                message=f"IXIA fault counters unchanged, but link(s) are "
                f"unhealthy right now: {'; '.join(link_failures)}",
            )
        return hc_types.HealthCheckResult(
            status=hc_types.HealthCheckStatus.PASS,
        )

    def enable_fault_statistics(self, ixia: Ixia) -> None:
        port_statistics = ixia.ixnetwork.Globals.Statistics.StatFilter.PortStatistics
        port_statistics.LinkState = "True"
        port_statistics.LinkFaultState = "True"
        port_statistics.LocalFaults = "True"
        port_statistics.RemoteFaults = "True"
        port_statistics.PcsLocalFaults = "True"
        port_statistics.PcsRemoteFaults = "True"

    @retryable(num_tries=3, sleep_time=2)
    def get_port_statistics(
        self,
        view: StatViewAssistant,
    ) -> t.List:
        stats = []
        view_name = view._ViewName
        # Informational columns are not present on every port type / IxNetwork
        # build. Reads MUST be guarded with `row.Columns`: restpy's Row treats
        # an unknown column string as a regex over cell CONTENTS, returning the
        # shared row cursor on a match (corrupting this very iteration) and
        # raising IndexError otherwise — it never returns None.
        present_info_columns: t.Optional[t.List[str]] = None
        for row in view.Rows:
            if present_info_columns is None:
                present_info_columns = [
                    column for column in INFO_COLUMNS if column in row.Columns
                ]
            stat = {
                "identifier": row["Port Name"],
                "CRC Errors": float(row["CRC Errors"]),
                "Local Faults": float(row["Local Faults"]),
                "Remote Faults": float(row["Remote Faults"]),
                "view": view_name,
            }
            for column in present_info_columns:
                stat[column] = row[column]
            stats.append(stat)
        return stats

    def verify_link_state(
        self, latest_stats: t.List[t.Dict[str, t.Any]]
    ) -> t.List[str]:
        """Assert the point-in-time link columns, where present.

        Value strings follow IxNetwork's Port Statistics view ("Link Up",
        "No Fault"); ports whose view lacks the columns are not asserted.
        """
        failures = []
        for stat in latest_stats:
            link_state = stat.get("Link State")
            if link_state not in (None, "n/a") and link_state != "Link Up":
                failures.append(f"{stat['identifier']}: Link State={link_state!r}")
            fault_state = stat.get("Link Fault State")
            if fault_state not in (None, "n/a") and fault_state != "No Fault":
                failures.append(
                    f"{stat['identifier']}: Link Fault State={fault_state!r}"
                )
        return failures

    def snapshot_fault_baseline(
        self,
        ixia: Ixia,
        latest_stats: t.List[t.Dict[str, t.Any]],
        ports: t.Optional[t.List[str]] = None,
    ) -> None:
        """Store the cumulative fault counters as the comparison baseline.

        Args:
            ixia: Owns the baseline for the lifetime of the test run.
            latest_stats: Rows from `get_port_statistics`.
            ports: Refresh only these ports, keeping the rest of the existing
                baseline. Replaces the whole baseline when omitted.

        The baseline is deliberately NOT advanced after a FAIL: a fault keeps
        failing every later invocation in the run rather than being reported
        once and absorbed.

        Ordering note: `IxiaPacketLossHealthCheck` clears port counters at the
        end of its run (`clear_traffic_stats` -> `ClearPortsAndTrafficStats`)
        unless `skip_clear_stats_at_end`. This check only reads the counters
        before that clear because it runs in an earlier priority group
        (DEFAULT_HC_PRIORITY=0 vs packet-loss's 40). Raising this check's
        priority to >= 40 would race it against the clear, with any fault in
        the window silently absorbed by the regression/re-baseline path.
        """
        baseline = dict(ixia.port_fault_baseline or {}) if ports is not None else {}
        for stat in latest_stats:
            identifier = stat["identifier"]
            if ports is not None and identifier not in ports:
                continue
            baseline[identifier] = {key: stat[key] for key in FAULT_COUNTERS}
        ixia.port_fault_baseline = baseline

    def compute_fault_deltas(
        self,
        latest_stats: t.List[t.Dict[str, t.Any]],
        baseline: t.Dict[str, t.Dict[str, float]],
    ) -> t.Tuple[t.List[t.Dict[str, t.Any]], t.List[str]]:
        """Subtract the baseline from each port's cumulative fault counters.

        A port missing from the baseline gets a zero baseline. Counters below
        the baseline are clamped to 0 — a negative delta would silently pass the
        threshold while the stale baseline hides real faults.

        Returns:
            (deltas, regressed_ports), where `regressed_ports` are the ports
            whose counters dropped below the baseline and so need re-baselining
            by the caller.
        """
        deltas = []
        regressed = []
        for stat in latest_stats:
            port_baseline = baseline.get(stat["identifier"], {})
            delta = dict(stat)
            for key in FAULT_COUNTERS:
                value = stat[key] - port_baseline.get(key, 0.0)
                if value < 0:
                    if stat["identifier"] not in regressed:
                        regressed.append(stat["identifier"])
                    value = 0.0
                delta[key] = value
            deltas.append(delta)
        return deltas, regressed

    def attribute_fault_direction(
        self, exceeded_thresholds: t.List[t.Dict[str, t.Any]]
    ) -> t.List[str]:
        """Map each port's new fault counters to the failing link direction.

        Deliberately reports a *direction* rather than a culprit: the counters
        cannot separate a far-end TX failure from a bad cable or a near-end RX
        failure. See DIRECTION_CAVEAT on the Local/Remote mapping itself.
        """
        attribution = []
        for stat in exceeded_thresholds:
            port = stat["identifier"]
            for counter, direction in DIRECTION_BY_COUNTER.items():
                if stat[counter] > 0:
                    attribution.append(
                        f"{port}: {counter} +{stat[counter]} => {direction}"
                    )
            fault_state = stat.get("Link Fault State")
            link_state = stat.get("Link State")
            if fault_state not in (None, "n/a") or link_state not in (None, "n/a"):
                attribution.append(
                    f"{port}: link state now={link_state}, "
                    f"link fault state now={fault_state}"
                )
        return attribution

    def verify_port_stats_threshold(
        self,
        latest_stats: t.List[t.Dict[str, t.Any]],
        threshold: float = 0.0,
    ) -> t.List[t.Dict[str, t.Any]]:
        """
        Verify if the port stats exceed the given threshold.

        Args:
            latest_stats: A list of port statistics.
            threshold: The threshold value to compare against (default is 0.0).

        Returns:
            A list of dictionaries containing the ports that exceeded the threshold.
        """
        exceeded_thresholds = []

        for stat in latest_stats:
            identifier = stat["identifier"]
            crc_errors = stat["CRC Errors"]
            local_faults = stat["Local Faults"]
            remote_faults = stat["Remote Faults"]

            if (
                crc_errors > threshold
                or local_faults > threshold
                or remote_faults > threshold
            ):
                exceeded = {
                    "identifier": identifier,
                    "CRC Errors": crc_errors,
                    "Local Faults": local_faults,
                    "Remote Faults": remote_faults,
                }
                # Fixed key set: tabulate(headers="keys") derives its column
                # set from the rows, so a column absent on some rows would
                # render a row-dependent table.
                for column in INFO_COLUMNS:
                    exceeded[column] = stat.get(column, "n/a")
                exceeded_thresholds.append(exceeded)

        return exceeded_thresholds
