# Copyright (c) Meta Platforms, Inc. and affiliates.
# pyre-strict

from __future__ import annotations

import typing as t
from dataclasses import dataclass, field


@dataclass
class CompiledTaacArtifacts:
    """Flat TAAC fragments generated by a future topology compiler."""

    endpoints: list[t.Any] = field(default_factory=list)
    host_os_type_map: dict[str, t.Any] = field(default_factory=dict)
    setup_tasks: list[t.Any] = field(default_factory=list)
    teardown_tasks: list[t.Any] = field(default_factory=list)
    basic_port_configs: list[t.Any] = field(default_factory=list)
    basic_traffic_item_configs: list[t.Any] = field(default_factory=list)
