# Copyright (c) Meta Platforms, Inc. and affiliates.

# pyre-unsafe
"""Reusable BGP-routed reboot TestConfig builder for FBOSS devices."""

import ipaddress
import json
import typing as t

from ixia.ixia import types as ixia_types
from taac.health_checks.healthcheck_definitions import (
    create_bgp_peer_route_snapshot_check,
    create_bgp_session_establish_check,
    create_core_dumps_snapshot_check,
    create_device_core_dumps_check,
    create_ixia_packet_loss_check,
    create_systemctl_active_state_check,
    create_unclean_exit_check,
    create_wedge_agent_configured_check,
)
from taac.playbooks.playbook_definitions import (
    create_system_reboot_playbooks,
)
from taac.task_definitions import (
    create_configure_parallel_bgp_peers_task,
    create_coop_apply_patchers_task,
    create_coop_register_patcher_task,
    create_coop_unregister_patchers_task,
    create_wait_for_agent_convergence_task,
)
from taac.testconfigs.routing.util.bgp_dc_tc_checks import (
    _PERMIT_ALL_POLICY_TERM,
)
from taac.health_check.health_check import types as hc_types
from taac.test_as_a_config import types as taac_types


def _increment_ip_addresses(
    *,
    starting_ip: str,
    increment_ip: str,
    count: int,
) -> list[str]:
    """Return every address generated by an IXIA increment pattern."""
    start = int(ipaddress.IPv6Address(starting_ip))
    increment = int(ipaddress.IPv6Address(increment_ip))
    return [
        str(ipaddress.IPv6Address(start + index * increment)) for index in range(count)
    ]


def _build_bgp_port_config(
    *,
    device_name: str,
    interface: str,
    ixia_ip_v6: str,
    dut_ip_v6: str,
    peer_prefix_length: int,
    advertised_prefix_v6: str,
    remote_as: int,
    device_group_multiplier: int,
) -> taac_types.BasicPortConfig:
    return taac_types.BasicPortConfig(
        endpoint=f"{device_name}:{interface}",
        device_group_configs=[
            taac_types.DeviceGroupConfig(
                device_group_index=0,
                multiplier=device_group_multiplier,
                v6_addresses_config=taac_types.IpAddressesConfig(
                    starting_ip=ixia_ip_v6,
                    increment_ip="::2",
                    gateway_starting_ip=dut_ip_v6,
                    gateway_increment_ip="::2",
                    mask=peer_prefix_length,
                ),
                v6_bgp_config=taac_types.BgpConfig(
                    local_as_4_bytes=remote_as,
                    local_as_increment=0,
                    enable_4_byte_local_as=True,
                    bgp_capabilities=[ixia_types.BgpCapability.IpV6Unicast],
                    hold_timer=30,
                    keepalive_timer=10,
                    route_scales=[
                        taac_types.RouteScaleSpec(
                            network_group_index=0,
                            v6_route_scale=taac_types.RouteScale(
                                multiplier=1,
                                prefix_count=16,
                                prefix_length=64,
                                starting_prefixes=advertised_prefix_v6,
                                prefix_step="0:0:0:1::",
                                ip_address_family=ixia_types.IpAddressFamily.IPV6,
                            ),
                        ),
                    ],
                ),
            ),
        ],
    )


def _build_parallel_peer_config(
    *,
    interface: str,
    dut_ip_v6: str,
    ixia_ip_v6: str,
    peer_prefix_length: int,
    peer_group_name: str,
    remote_as: int,
    device_group_multiplier: int,
    vlan_id: t.Optional[int] = None,
    retain_existing_vlan_addresses: bool = True,
) -> dict[str, list[dict[str, object]]]:
    config: dict[str, object] = {
        "starting_ip": dut_ip_v6,
        "increment_ip": "::2",
        "prefix_length": peer_prefix_length,
        "description": "TAAC reboot IPv6 BGP peer",
        "peer_group_name": peer_group_name,
        "num_sessions": device_group_multiplier,
        "remote_as_4_byte": remote_as,
        "remote_as_4_byte_step": 0,
        "gateway_starting_ip": ixia_ip_v6,
        "gateway_increment_ip": "::2",
        "retain_existing_vlan_addresses": retain_existing_vlan_addresses,
    }
    if vlan_id is not None:
        config["vlan_id"] = vlan_id
    return {interface: [config]}


def create_npi_bgp_reboot_test_config(
    *,
    test_config_name: str,
    device_name: str,
    device_role: str,
    ixia_source_interface: str,
    ixia_destination_interface: str,
    source_dut_ip_v6: str,
    destination_dut_ip_v6: str,
    source_ixia_ip_v6: str,
    destination_ixia_ip_v6: str,
    peer_prefix_length: int,
    source_advertised_prefix_v6: str,
    destination_advertised_prefix_v6: str,
    remote_as: int = 65000,
    source_remote_as: t.Optional[int] = None,
    destination_remote_as: t.Optional[int] = None,
    source_vlan_id: t.Optional[int] = None,
    destination_vlan_id: t.Optional[int] = None,
    device_group_multiplier: int = 20,
    peer_group_name: str = "TAAC_REBOOT_IXIA_V6",
    basset_pool: str = "dne.regression",
    iteration: int = 1,
    line_rate: int = 10,
    frame_size_settings: t.Optional[ixia_types.FrameSize] = None,
    direct_ixia_connections: t.Optional[t.List[taac_types.DirectIxiaConnection]] = None,
) -> taac_types.TestConfig:
    """Create one full-reboot case over two IXIA eBGP peers.

    Non-RSW devices retain the standard per-port VLAN/IP behavior. RSW callers
    provide the VLAN split validated against the live topology: the lowest
    IXIA-facing port remains on VLAN 2000 and additional ports move to their
    dedicated VLANs.
    """
    traffic_item_name = f"{device_name.upper()}_REBOOT_ROUTED_V6"
    ingress_policy = f"PROPAGATE_EVERYTHING_{peer_group_name}_IN"
    egress_policy = f"PROPAGATE_EVERYTHING_{peer_group_name}_OUT"
    is_rsw = device_role.upper() == "RSW"
    if is_rsw and (source_vlan_id is None or destination_vlan_id is None):
        raise ValueError("RSW BGP reboot configs require explicit per-port VLAN IDs")
    if device_group_multiplier < 20:
        raise ValueError("BGP reboot tests require at least 20 devices per IXIA port")
    source_remote_as = remote_as if source_remote_as is None else source_remote_as
    destination_remote_as = (
        remote_as if destination_remote_as is None else destination_remote_as
    )
    config_names = ["bgpcpp"] if is_rsw else ["bgpcpp", "bgpcpp_softdrain"]
    unregister_config_names = ["agent", *config_names]

    setup_tasks = [
        create_coop_unregister_patchers_task(
            device_name,
            config_names=unregister_config_names,
        ),
        create_coop_register_patcher_task(
            hostname=device_name,
            config_names=config_names,
            patcher_name=f"a_add_bgp_policy_statement_{ingress_policy}",
            task_name="coop_register_patcher",
            patcher_args={
                "name": ingress_policy,
                "description": "Accept all TAAC reboot-test prefixes",
                "policy_entries": json.dumps([_PERMIT_ALL_POLICY_TERM]),
            },
            py_func_name="add_bgp_policy_statement",
        ),
        create_coop_register_patcher_task(
            hostname=device_name,
            config_names=config_names,
            patcher_name=f"a_add_bgp_policy_statement_{egress_policy}",
            task_name="coop_register_patcher",
            patcher_args={
                "name": egress_policy,
                "description": "Advertise all TAAC reboot-test prefixes",
                "policy_entries": json.dumps([_PERMIT_ALL_POLICY_TERM]),
            },
            py_func_name="add_bgp_policy_statement",
        ),
        create_coop_register_patcher_task(
            hostname=device_name,
            config_names=config_names,
            patcher_name=f"b_add_peer_group_{peer_group_name}",
            task_name="coop_register_patcher",
            patcher_args={
                "name": peer_group_name,
                "description": "TAAC routed reboot-test peers",
                "next_hop_self": "True",
                "disable_ipv4_afi": "True",
                "disable_ipv6_afi": "False",
                "is_confed_peer": "False",
                "ingress_policy_name": ingress_policy,
                "egress_policy_name": egress_policy,
                "bgp_peer_timers_hold_time_seconds": "30",
                "bgp_peer_timers_keep_alive_seconds": "10",
                "bgp_peer_timers_out_delay_seconds": "0",
                "bgp_peer_timers_withdraw_unprog_delay_seconds": "0",
                "peer_tag": "IXIA",
                "max_routes": "1000",
                "warning_only": "True",
                "warning_limit": "0",
                "link_bandwidth_bps": "auto",
                "v4_over_v6_nexthop": "False",
                "is_passive": "False",
            },
            py_func_name="add_peer_group_patcher",
        ),
        create_configure_parallel_bgp_peers_task(
            hostname=device_name,
            configure_vlans_patcher_name="configure_vlans_reboot_test",
            add_bgp_peers_patcher_name="add_bgp_peers_reboot_test",
            config_json=json.dumps(
                {
                    **_build_parallel_peer_config(
                        interface=ixia_source_interface,
                        dut_ip_v6=source_dut_ip_v6,
                        ixia_ip_v6=source_ixia_ip_v6,
                        peer_prefix_length=peer_prefix_length,
                        peer_group_name=peer_group_name,
                        remote_as=source_remote_as,
                        device_group_multiplier=device_group_multiplier,
                        vlan_id=source_vlan_id,
                        retain_existing_vlan_addresses=not is_rsw,
                    ),
                    **_build_parallel_peer_config(
                        interface=ixia_destination_interface,
                        dut_ip_v6=destination_dut_ip_v6,
                        ixia_ip_v6=destination_ixia_ip_v6,
                        peer_prefix_length=peer_prefix_length,
                        peer_group_name=peer_group_name,
                        remote_as=destination_remote_as,
                        device_group_multiplier=device_group_multiplier,
                        vlan_id=destination_vlan_id,
                        retain_existing_vlan_addresses=not is_rsw,
                    ),
                }
            ),
            shared_vlan_id=2000 if is_rsw else None,
        ),
        create_coop_apply_patchers_task(hostnames=[device_name]),
        create_wait_for_agent_convergence_task([device_name]),
    ]

    ixia_peer_addresses = [
        *_increment_ip_addresses(
            starting_ip=source_ixia_ip_v6,
            increment_ip="::2",
            count=device_group_multiplier,
        ),
        *_increment_ip_addresses(
            starting_ip=destination_ixia_ip_v6,
            increment_ip="::2",
            count=device_group_multiplier,
        ),
    ]
    bgp_check = create_bgp_session_establish_check(
        ignore_all_prefixes_except=ixia_peer_addresses,
        expected_established_sessions=2 * device_group_multiplier,
        retry_count=10,
        retry_delay_seconds=15,
        retry_delay_multiplier=1.0,
    )
    packet_loss_threshold = hc_types.PacketLossThreshold(
        names=[traffic_item_name],
        metric=hc_types.PacketLossMetric.PERCENTAGE,
        str_value="0",
        expect_packet_loss=False,
        comparison=hc_types.ComparisonType.LESS_THAN_EQUAL_TO,
    )
    loss_precheck = create_ixia_packet_loss_check(
        thresholds=[packet_loss_threshold],
        clear_traffic_stats=True,
    )
    loss_postcheck = create_ixia_packet_loss_check(
        thresholds=[packet_loss_threshold],
        clear_traffic_stats=True,
    )
    stable_loss_postcheck = create_ixia_packet_loss_check(
        thresholds=[packet_loss_threshold],
        clear_traffic_stats=False,
    )
    operational_checks = [
        bgp_check,
        create_systemctl_active_state_check(),
        create_wedge_agent_configured_check(),
    ]
    playbooks = []
    for playbook_name, reboot_trigger in (
        (
            "test_system_reboot_bmc_full",
            taac_types.SystemRebootTrigger.FULL_SYSTEM_REBOOT,
        ),
        (
            "test_system_reboot_bmc_microserver",
            taac_types.SystemRebootTrigger.BMC_POWER_RESET,
        ),
        (
            "test_system_reboot_microserver",
            taac_types.SystemRebootTrigger.BMC_MICROSERVER_ONLY_RESET,
        ),
    ):
        playbooks.extend(
            create_system_reboot_playbooks(
                name=playbook_name,
                trigger=reboot_trigger,
                is_rsw=is_rsw,
                iteration=iteration,
                recovery_prechecks=[*operational_checks, loss_precheck],
                recovery_postchecks=[*operational_checks, loss_postcheck],
                stability_prechecks=[*operational_checks, loss_precheck],
                stability_postchecks=[
                    *operational_checks,
                    stable_loss_postcheck,
                    create_unclean_exit_check(),
                    create_device_core_dumps_check(),
                ],
                stability_snapshot_checks=[
                    create_core_dumps_snapshot_check(),
                    create_bgp_peer_route_snapshot_check(),
                ],
                traffic_items_to_start=[traffic_item_name],
                recovery_duration_s=240,
                stability_duration_s=300,
            )
        )

    return taac_types.TestConfig(
        name=test_config_name,
        basset_pool=basset_pool,
        endpoints=[
            taac_types.Endpoint(
                name=device_name,
                dut=True,
                ixia_needed=True,
                ixia_ports=[ixia_source_interface, ixia_destination_interface],
                direct_ixia_connections=direct_ixia_connections or [],
            )
        ],
        setup_tasks=setup_tasks,
        teardown_tasks=[
            create_coop_unregister_patchers_task(
                device_name,
                config_names=unregister_config_names,
            )
        ],
        basic_port_configs=[
            _build_bgp_port_config(
                device_name=device_name,
                interface=ixia_source_interface,
                ixia_ip_v6=source_ixia_ip_v6,
                dut_ip_v6=source_dut_ip_v6,
                peer_prefix_length=peer_prefix_length,
                advertised_prefix_v6=source_advertised_prefix_v6,
                remote_as=source_remote_as,
                device_group_multiplier=device_group_multiplier,
            ),
            _build_bgp_port_config(
                device_name=device_name,
                interface=ixia_destination_interface,
                ixia_ip_v6=destination_ixia_ip_v6,
                dut_ip_v6=destination_dut_ip_v6,
                peer_prefix_length=peer_prefix_length,
                advertised_prefix_v6=destination_advertised_prefix_v6,
                remote_as=destination_remote_as,
                device_group_multiplier=device_group_multiplier,
            ),
        ],
        basic_traffic_item_configs=[
            taac_types.BasicTrafficItemConfig(
                name=traffic_item_name,
                bidirectional=True,
                merge_destinations=True,
                line_rate=line_rate,
                src_dest_mesh=ixia_types.SrcDestMeshType.MANY_TO_MANY,
                src_endpoints=[
                    taac_types.TrafficEndpoint(
                        name=f"{device_name}:{ixia_source_interface}",
                        device_group_index=0,
                        network_group_index=0,
                    )
                ],
                dest_endpoints=[
                    taac_types.TrafficEndpoint(
                        name=f"{device_name}:{ixia_destination_interface}",
                        device_group_index=0,
                        network_group_index=0,
                    )
                ],
                traffic_type=ixia_types.TrafficType.IPV6,
                frame_size_settings=frame_size_settings,
            )
        ],
        playbooks=playbooks,
        ixia_config_cache=taac_types.IxiaConfigCache(enabled=False),
    )
