# Copyright (c) Meta Platforms, Inc. and affiliates.

# pyre-strict

MINIPACK_CPU_QUEUE_PLAYBOOKS: list[str] = [
    "npi_cpu_001_lldp_mcast_to_mid_queue",
    "npi_cpu_002_bgp_cp_v6_global_dscp48_to_high_queue",
    "npi_cpu_003_bgp_cp_v6_link_local_dscp48_to_high_queue",
    "npi_cpu_004_bgp_cp_v6_link_local_dscp0_to_high_queue",
    "npi_cpu_005_bgp_cp_v4_def_gw_dscp48_to_high_queue",
    "npi_cpu_006_bgp_cp_v4_def_gw_dscp0_to_high_queue",
    "npi_cpu_007_dhcp_v6_global_dscp48_to_mid_queue",
    "npi_cpu_008_dhcp_v6_global_dscp0_to_mid_queue",
    "npi_cpu_009_dhcp_v6_ll_dscp48_to_mid_queue",
    "npi_cpu_010_dhcp_v4_discover_bcast_to_mid_queue",
    "npi_cpu_011_dhcp_v4_discover_ucast_to_mid_queue",
    "npi_cpu_012_icmp_v4_echo_req_to_mid_queue",
    "npi_cpu_013_icmp_v4_echo_reply_to_mid_queue",
    "npi_cpu_014_icmp_v4_dest_unreach_to_mid_queue",
    "npi_cpu_015_icmp_v4_time_exceeded_to_mid_queue",
    "npi_cpu_019_arp_response_bcast_to_high_queue",
    "npi_cpu_016_icmp_v6_echo_req_ll_to_mid_queue",
    "npi_cpu_021_ndp_ns_ll_dscp48_to_high_queue",
    "npi_cpu_017_arp_request_bcast_to_high_queue",
    "npi_cpu_018_arp_response_to_high_queue",
    "npi_cpu_020_ndp_ns_global_dscp48_to_high_queue",
    "npi_cpu_039_mtu_exceed_to_low_queue",
    "npi_cpu_033_ndp_na_ll_to_high_queue",
    "npi_cpu_034_ndp_rs_mcast_to_high_queue",
    "npi_cpu_035_ndp_ra_ll_to_high_queue",
    "npi_cpu_038_unh_remote_host_route_to_low_queue",
    "npi_cpu_037_unh_remote_subnet_to_low_queue",
    "npi_cpu_036_unh_dir_conn_host_to_low_queue",
    "npi_cpu_046_martian_sip_not_punted",
    "npi_cpu_040_lacp_mcast_to_high_queue",
    "npi_cpu_041_queue_prioritization_high_no_drops",
    "npi_cpu_042_hop_limit_1_to_low_queue",
    "npi_cpu_043_hop_limit_0_not_punted",
    "npi_cpu_044_ttl_1_ipv4_to_low_queue",
    "npi_cpu_045_ttl_0_ipv4_not_punted",
    "npi_cpu_047_dscp_48_to_switch_global_to_mid_queue",
    "npi_cpu_048_dscp_48_to_switch_ll_to_mid_queue",
]
