# Copyright (c) Meta Platforms, Inc. and affiliates.

# pyre-unsafe
"""Minipack/Tomahawk3 CPU-queue qualification on fsw004.p003.f01.qzd1."""

from taac.testconfigs.npi.cpu_queue_test_config import (
    create_npi_cpu_queue_test_config,
)


_CPUQ_PLAYBOOKS = [
    "npi_cpu_001_lldp_mcast_to_mid_queue",
    "npi_cpu_002_bgp_cp_v6_global_dscp48_to_high_queue",
    "npi_cpu_003_bgp_cp_v6_link_local_dscp48_to_high_queue",
    "npi_cpu_004_bgp_cp_v6_link_local_dscp0_to_high_queue",
    "npi_cpu_005_bgp_cp_v4_def_gw_dscp48_to_high_queue",
    "npi_cpu_006_bgp_cp_v4_def_gw_dscp0_to_high_queue",
    "npi_cpu_007_dhcp_v6_global_dscp48_to_mid_queue",
    "npi_cpu_008_dhcp_v6_global_dscp0_to_mid_queue",
    "npi_cpu_009_dhcp_v6_ll_dscp48_to_mid_queue",
    "npi_cpu_010_dhcp_v4_discover_bcast_to_mid_queue",
    "npi_cpu_011_dhcp_v4_discover_ucast_to_mid_queue",
    "npi_cpu_012_icmp_v4_echo_req_to_mid_queue",
    "npi_cpu_013_icmp_v4_echo_reply_to_mid_queue",
    "npi_cpu_014_icmp_v4_dest_unreach_to_mid_queue",
    "npi_cpu_015_icmp_v4_time_exceeded_to_mid_queue",
    "npi_cpu_019_arp_response_bcast_to_high_queue",
    "npi_cpu_016_icmp_v6_echo_req_ll_to_mid_queue",
    "npi_cpu_021_ndp_ns_ll_dscp48_to_high_queue",
    "npi_cpu_017_arp_request_bcast_to_high_queue",
    "npi_cpu_018_arp_response_to_high_queue",
    "npi_cpu_020_ndp_ns_global_dscp48_to_high_queue",
    "npi_cpu_039_mtu_exceed_to_low_queue",
    "npi_cpu_033_ndp_na_ll_to_high_queue",
    "npi_cpu_034_ndp_rs_mcast_to_high_queue",
    "npi_cpu_035_ndp_ra_ll_to_high_queue",
    "npi_cpu_038_unh_remote_host_route_to_low_queue",
    "npi_cpu_037_unh_remote_subnet_to_low_queue",
    "npi_cpu_036_unh_dir_conn_host_to_low_queue",
    "npi_cpu_046_martian_sip_not_punted",
    "npi_cpu_040_lacp_mcast_to_high_queue",
    "npi_cpu_041_queue_prioritization_high_no_drops",
    "npi_cpu_042_hop_limit_1_to_low_queue",
    "npi_cpu_043_hop_limit_0_not_punted",
    "npi_cpu_044_ttl_1_ipv4_to_low_queue",
    "npi_cpu_045_ttl_0_ipv4_not_punted",
    "npi_cpu_047_dscp_48_to_switch_global_to_mid_queue",
    "npi_cpu_048_dscp_48_to_switch_ll_to_mid_queue",
]


MINIPACK_FSW004_P003_QZD1_CPU_QUEUE_TEST_CONFIG = create_npi_cpu_queue_test_config(
    test_config_name="MINIPACK_FSW004_P003_QZD1_CPU_QUEUE_TEST_CONFIG",
    device_name="fsw004.p003.f01.qzd1",
    local_mac_address="c2:18:50:99:92:2d",
    ixia_downlink_interface="eth7/16/1",
    ixia_uplink_interface="eth9/16/1",
    ixia_rogue_interface="eth8/16/1",
    peergroup_uplink_mimic_v6="PEERGROUP_FSW_SSW_V6",
    peergroup_downlink_mimic_v6="PEERGROUP_FSW_RSW_V6",
    peergroup_uplink_mimic_v4="PEERGROUP_FSW_SSW_V4",
    peergroup_downlink_mimic_v4="PEERGROUP_FSW_RSW_V4",
    peergroup_rogue_mimic_v6="PEERGROUP_FSW_SSW_V6",
    peergroup_rogue_mimic_v4="PEERGROUP_FSW_SSW_V4",
    route_map_uplink_ingress="PROPAGATE_FSW_SSW_IN",
    route_map_uplink_egress="PROPAGATE_FSW_SSW_OUT",
    route_map_downlink_ingress="PROPAGATE_FSW_RSW_IN",
    route_map_downlink_egress="PROPAGATE_FSW_RSW_OUT",
    route_map_rogue_ingress="PROPAGATE_FSW_SSW_IN",
    route_map_rogue_egress="PROPAGATE_FSW_SSW_OUT",
    ixia_downlink_ic_parent_network_v6="2401:db00:e50d:11:8",
    ixia_uplink_ic_parent_network_v6="2401:db00:e50d:11:9",
    ixia_rogue_ic_parent_network_v6="2401:db00:e50d:11:10",
    ixia_downlink_ic_parent_network_v4="10.163.28",
    ixia_uplink_ic_parent_network_v4="10.164.29",
    ixia_rogue_ic_parent_network_v4="10.165.28",
    unique_prefix_limit="5000",
    per_peer_max_route_limit="20000",
    downlink_peer_count=8,
    uplink_peer_count=8,
    rogue_peer_count=0,
    remote_uplink_as_4byte=65000,
    remote_downlink_as_4byte=2000,
    remote_as_4_byte_step=1,
    remote_rogue_as_4byte=2500,
    is_uplink_peer_confed="False",
    is_downlink_peer_confed="True",
    is_rogue_peer_confed="False",
    ixia_downlink_prefix_count_v6=500,
    ixia_uplink_prefix_count_v6=500,
    ixia_rogue_prefix_count_v6=0,
    ixia_downlink_prefix_count_v4=500,
    ixia_uplink_prefix_count_v4=500,
    ixia_rogue_prefix_count_v4=0,
    ixia_downlink_communities=[
        "65441:194",
        "65441:9001",
        "65441:9002",
        "65441:9003",
        "65441:9004",
        "65441:9005",
    ],
    ixia_uplink_communities=[
        "65441:196",
        "65441:9001",
        "65441:9002",
        "65441:9003",
        "65441:9004",
        "65441:9005",
    ],
    uplink_peer_tag="SSW",
    downlink_peer_tag="RSW",
    basset_pool="dne.regression",
    low_queue=0,
    mid_queue=2,
    high_queue=9,
    playbooks_selected=_CPUQ_PLAYBOOKS,
    restore_soft_drain=True,
)


__all__ = ["MINIPACK_FSW004_P003_QZD1_CPU_QUEUE_TEST_CONFIG"]
